### ISSUE TITLE
Fix New 500 Errors

### ISSUE THREAD

**Issue by TheJoshuaEvans** [TheJoshuaEvans/project-leap#10]
After doing the latest push, 500 errors have been popping up extremely frequently. This needs to be fixed ASAP

**Comment by TheJoshuaEvans** [comment]
This error from the Lambda logs is interesting:
```
<html>
<body>
<!--StartFragment-->

@ingestionTime | 1670628762382
-- | --
@log | 448495040557:/aws/lambda/prodMoonBackendStack-RouterFunction6AC6EF3B-qRWgCT8MdpIs
@logStream | 2022/12/09/[$LATEST]794d7b23b66c4c0bbb062e862f344e42
@message | 2022-12-09T23:32:42.242Z 192f3905-1153-450b-b9fc-0876e6e78add ERROR Unhandled Promise Rejection {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Converting circular structure to JSON\n --> starting at object with constructor 'TLSSocket'\n \| property '_httpMessage' -> object with constructor 'ClientRequest'\n --- property 'socket' closes the circle","reason":{"errorType":"TypeError","errorMessage":"Converting circular structure to JSON\n --> starting at object with constructor 'TLSSocket'\n \| property '_httpMessage' -> object with constructor 'ClientRequest'\n --- property 'socket' closes the circle","stack":["TypeError: Converting circular structure to JSON"," --> starting at object with constructor 'TLSSocket'"," \| property '_httpMessage' -> object with constructor 'ClientRequest'"," --- property 'socket' closes the circle"," at JSON.stringify (<anonymous>)"," at onError (/var/task/index.js:117:10154)"," at RGe (/var/task/index.js:104:948)"," at processTicksAndRejections (internal/process/task_queues.js:95:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Converting circular structure to JSON"," --> starting at object with constructor 'TLSSocket'"," \| property '_httpMessage' -> object with constructor 'ClientRequest'"," --- property 'socket' closes the circle"," at process.<anonymous> (/var/runtime/index.js:35:15)"," at process.emit (events.js:400:28)"," at processPromiseRejections (internal/process/promises.js:245:33)"," at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
@requestId | 192f3905-1153-450b-b9fc-0876e6e78add
@timestamp | 1670628762242
errorMessage | TypeError: Converting circular structure to JSON--> starting at object with constructor 'TLSSocket'\| property '_httpMessage' -> object with constructor 'ClientRequest'--- property 'socket' closes the circle
errorType | Runtime.UnhandledPromiseRejection
reason.errorMessage | Converting circular structure to JSON--> starting at object with constructor 'TLSSocket'\| property '_httpMessage' -> object with constructor 'ClientRequest'--- property 'socket' closes the circle
reason.errorType | TypeError
reason.stack.0 | TypeError: Converting circular structure to JSON
reason.stack.1 | --> starting at object with constructor 'TLSSocket'
reason.stack.2 | \| property '_httpMessage' -> object with constructor 'ClientRequest'
reason.stack.3 | --- property 'socket' closes the circle
reason.stack.4 | at JSON.stringify (<anonymous>)
reason.stack.5 | at onError (/var/task/index.js:117:10154)
reason.stack.6 | at RGe (/var/task/index.js:104:948)
reason.stack.7 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
stack.0 | Runtime.UnhandledPromiseRejection: TypeError: Converting circular structure to JSON
stack.1 | --> starting at object with constructor 'TLSSocket'
stack.2 | \| property '_httpMessage' -> object with constructor 'ClientRequest'
stack.3 | --- property 'socket' closes the circle
stack.4 | at process.<anonymous> (/var/runtime/index.js:35:15)
stack.5 | at process.emit (events.js:400:28)
stack.6 | at processPromiseRejections (internal/process/promises.js:245:33)
stack.7 | at processTicksAndRejections (internal/process/task_queues.js:96:32)

<!--EndFragment-->
</body>
</html>
```

**Comment by TheJoshuaEvans** [comment]
From Moon:
```
7:14 PM]Torin Stepan: I'm running into a few intermittent problems with some backend methods
[7:15 PM]Torin Stepan: I'll add more details on more exact sample data / usages to make investigation easier shortly
[7:16 PM]Torin Stepan: one case is:
- Upsert a session
- Periodically update the session
sometimes (seemingly more likely on the first call? but possibly periodically) the session can't be found
System.AggregateException: One or more errors occurred. (Could not find item from "sessions" table with id "2812743a-df25-4937-8da9-aee4c5136351")
 ---> MoonBackend.Exceptions.NotFoundException: Could not find item from "sessions" table with id "2812743a-df25-4937-8da9-aee4c5136351"
   at MoonBackend.Methods.MethodsBase.ThrowNotFound(Object item, String table, String id, String realmId) in /home/runner/work/MoonBackend/MoonBackend/MoonBackendSDK/Shared/Methods/MethodsBase/MethodsBaseThrowChecks.cs:line 43
   at MoonBackend.Methods.SessionsMethods.UpdateSession[TInfo](ISession`1 session, Nullable`1 expiresIn) in /home/runner/work/MoonBackend/MoonBackend/MoonBackendSDK/MoonBackendSDKDedicated/Methods/SessionsMethods.cs:line 138

but after failing and just periodically continuing to update, this will find the session and succeed 
[7:18 PM]Torin Stepan: another case, very similar: trying to save a character
System.AggregateException: One or more errors occurred. (Could not find item from "characters" table with id "847d38f0-2ade-4463-83e8-f5138a2c2149")
 ---> MoonBackend.Exceptions.NotFoundException: Could not find item from "characters" table with id "847d38f0-2ade-4463-83e8-f5138a2c2149"
   at MoonBackend.Methods.MethodsBase.ThrowNotFound(Object item, String table, String id, String realmId) in /home/runner/work/MoonBackend/MoonBackend/MoonBackendSDK/Shared/Methods/MethodsBase/MethodsBaseThrowChecks.cs:line 43
   at MoonBackend.Methods.CharactersMethods.UpdateCharacter[TInfo](ICharacter`1 character) in /home/runner/work/MoonBackend/MoonBackend/MoonBackendSDK/Shared/Methods/CharactersMethods.cs:line 112


doesn't happen every time, and the character definitely exists in the prod DB (I haven't run into a problem loading that particular character yet, and it also saves successfully sometimes, but sometimes hits this and fails)
[7:19 PM]Torin Stepan: another issue we saw a bit of in the server log, hoped that the sdk update would resolve, but I just ran into it trying to call get characters:
ArgumentNullException: Value cannot be null.

Parameter name: source
System.Linq.Enumerable.Select[TSource,TResult] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] selector) (at <1e18c5a6594041c9844bfd0b6618ee4a>:0)
MoonBackend.Methods.MethodsBase.Migrate[TInfo] (System.Collections.Generic.IEnumerable`1[T] data) (at /home/runner/work/MoonBackend/MoonBackend/MoonBackendSDK/Shared/Methods/MethodsBase/MethodsBaseMigration.cs:235)
MoonBackend.Methods.CharactersMethods.GetCharacters[TInfo] () (at /home/runner/work/MoonBackend/MoonBackend/MoonBackendSDK/Shared/Methods/CharactersMethods.cs:35)
Rethrow as AggregateException: One or more errors occurred. (Value cannot be null.
[7:19 PM]Torin Stepan: the exact same get characters call then succeeds on a 2nd attempt
[7:21 PM]Torin Stepan: the characters one is simple:
await m_sdk.characters.GetCharacters<CharacterModel>();
[7:28 PM]Torin Stepan: usage of the session update:
Image
[7:28 PM]Torin Stepan: with the data in the session as follows:
Image
[7:29 PM]Torin Stepan: usage of the character update - characterId is 847d38f0-2ade-4463-83e8-f5138a2c2149, characterData is a byte array (size around 3000) of some stuff
Image
[7:30 PM]Torin Stepan: now, worth noting that both times I stopped here debugging, these calls succeeded (and seem to usually succeed)
[7:30 PM]Torin Stepan: but it was the same data occasionally causing failures
[7:35 PM]Torin Stepan: all of these errors from my local testing occurred from 18:24-19:08 PST today
[7:36 PM]Torin Stepan: there's also a spike of similar errors mostly along the lines of this: 
---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MoonBackend.Methods.MethodsBase.Deserialize[TData](String body) in C:\Users\TheJo\Development\MoonBackend\MoonBackendSDK\Shared\Methods\MethodsBase\MethodsBaseApiRequest.cs:line 126
   at MoonBackend.Methods.MethodsBase.ApiRequest[TData](IApiRequestOpts opts) in C:\Users\TheJo\Development\MoonBackend\MoonBackendSDK\Shared\Methods\MethodsBase\MethodsBaseApiRequest.cs:line 54
   at MoonBackend.Methods.MethodsBase.ApiRequest[T](HttpMethod method, String endpoint, Object requestBody, QueryParameters query, String versionEndpoint) in C:\Users\TheJo\Development\MoonBackend\MoonBackendSDK\Shared\Methods\MethodsBase\MethodsBaseApiRequest.cs:line 77
   at MoonBackend.Methods.MethodsBase.ApiRequestPut[T](String endpoint, Object requestBody, QueryParameters query) in C:\Users\TheJo\Development\MoonBackend\MoonBackendSDK\Shared\Methods\MethodsBase\MethodsBaseApiRequest.cs:line 197
   at MoonBackend.Methods.SessionsMethods.UpdateSession[TInfo](ISession`1 session, Nullable`1 expiresIn) in C:\Users\TheJo\Development\MoonBackend\MoonBackendSDK\MoonBackendSDKDedicated\Methods\SessionsMethods.cs:line 132
   at MoonBackend.Methods.SessionsMethods.UpsertSession[TInfo](ISession`1 session, Nullable`1 expiresIn) in C:\Users\TheJo\Development\MoonBackend\MoonBackendSDK\MoonBackendSDKDedicated\Methods\SessionsMethods.cs:line 157

between 02:00 and 13:00 PST -- though these are on an older sdk version
```

**Comment by TheJoshuaEvans** [comment]
Opps, wrong repo :O
